# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: PM-Dungeon - CI with Maven

on: push

jobs:
  build:
    
    runs-on: ubuntu-latest  # ? Ubuntu 20.04

    steps:
    # downloads copy of repo to the runner
    - uses: actions/checkout@v2
    
    # Setup JDK 11
    - name: Set up JDK 11 #
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt' # Adopt OpenJDK HotSpot
        java-package: 'jdk' #is default
        # architecture: x64 --> wichtig?
        
    # Caching Dependencies to speed up
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    # Building project(includes testing, and static code analysis)
      # --errors: produce execution error messages
      # -B: non-interactiv btach mode
      # --file: force the use of an alternative POM
    - name: Checkstyle
      run: mvn -B checkstyle:check --file pom.xml --errors --fail-at-end
    - name: Spotbugs
      run: mvn -B spotbugs:check --file pom.xml --errors --fail-at-end
    - name: PMD
      run: mvn -B pmd:check pmd:cpd-check --file pom.xml --errors --fail-at-end
    - name: Unit Testing
      run: mvn -B verify --file pom.xml --errors --fail-at-end
      
    # MAYBE: stage documentation via actions/upload-artifact@v2
